/**
 * Claims for the Nairobi case (part 1: the Pumwani cluster).
 * `excerpt` is verbatim from the source. review_state: approved (human-verified),
 * extraction_method: manual.
 */

export const seedClaimsPumwani = [
  // ── Lucky Summer Dispensary ────────────────────────────────────────────
  { key: "ls-award", projectKey: "lucky-summer", docKey: "oag-2223", partyKey: "contractor-a", stage: "award", kind: "award_made", amountKes: 869_000_000, eventDate: null, observedStatus: "stalled", assertion: "One contractor was engaged to construct three health facilities — Lucky Summer Dispensary, Pumwani Majengo Health Centre and Gumba/Mabatini Dispensary — at a combined KSh 869,000,000. All three projects stalled.", excerpt: "one contractor was engaged to construct three health facilities at a sum of Sh869 million but all the projects stalled. The projects included the construction and equipping of Pumwani Lucky Summer Dispensary, Pumwani Majengo Health Centre and Gumba/Mabatini Dispensary" },
  { key: "ls-insp", projectKey: "lucky-summer", docKey: "oag-2223", stage: "implementation", kind: "inspection_finding", amountKes: null, eventDate: "2023-09-28", observedStatus: "not_started", assertion: "OAG field inspection (28–29 Sept 2023): Lucky Summer Dispensary had barely started and the building is dilapidated.", excerpt: "Field inspection on these projects carried out on September 28 and 29, 2023 revealed they were not complete... the Lucky Summer Dispensary barely started and the building is dilapidated" },
  { key: "ls-star", projectKey: "lucky-summer", docKey: "star-2024", stage: "implementation", kind: "inspection_finding", amountKes: null, eventDate: "2024-04-19", observedStatus: "not_started", assertion: "The Star, quoting the OAG report: Lucky Summer Dispensary 'barely started and the building is dilapidated'.", excerpt: "the Lucky Summer Dispensary barely started and the building is dilapidated" },
  { key: "ls-willow", projectKey: "lucky-summer", docKey: "willow-2026", stage: "completion", kind: "delivery_observed", amountKes: null, eventDate: "2026-07-03", observedStatus: "not_started", assertion: "Willow Health Media site reporting (July 2026): Lucky Summer dispensary had barely started — nearly three years after the audit.", excerpt: "Wall at Pumwani Majengo hadn't been built, Lucky Summer dispensary had barely started" },

  // ── Pumwani Majengo Health Centre ──────────────────────────────────────
  { key: "mj-award", projectKey: "majengo", docKey: "oag-2223", partyKey: "contractor-a", stage: "award", kind: "award_made", amountKes: 869_000_000, eventDate: null, observedStatus: "stalled", assertion: "Majengo Health Centre was one of the three facilities under the single KSh 869,000,000 contract that stalled.", excerpt: "one contractor was engaged to construct three health facilities at a sum of Sh869 million but all the projects stalled" },
  { key: "mj-insp", projectKey: "majengo", docKey: "oag-2223", stage: "implementation", kind: "inspection_finding", amountKes: null, eventDate: "2023-09-28", observedStatus: "stalled", assertion: "OAG field inspection (28–29 Sept 2023): Majengo not complete and not labelled; the perimeter wall was not done.", excerpt: "they were not complete and labelled, the perimeter wall was not done for Pumwani Majengo Health Center" },
  { key: "mj-willow", projectKey: "majengo", docKey: "willow-2026", stage: "completion", kind: "delivery_observed", amountKes: null, eventDate: "2026-07-03", observedStatus: "stalled", assertion: "Willow Health Media (July 2026): construction at Pumwani Majengo has stalled despite millions allocated; perimeter wall still not built.", excerpt: "Construction at Pumwani Majengo Health Centre has stalled despite millions of shillings allocated for the project" },
] as const;

export const seedClaimsGumba = [
  { key: "gm-award", projectKey: "gumba-mabatini", docKey: "oag-2223", partyKey: "contractor-a", stage: "award", kind: "award_made", amountKes: 869_000_000, eventDate: null, observedStatus: "stalled", assertion: "Gumba/Mabatini Dispensary was one of the three facilities under the single KSh 869,000,000 contract that stalled.", excerpt: "The projects included the construction and equipping of Pumwani Lucky Summer Dispensary, Pumwani Majengo Health Centre and Gumba/Mabatini Dispensary" },
  { key: "gm-insp", projectKey: "gumba-mabatini", docKey: "oag-2223", stage: "implementation", kind: "inspection_finding", amountKes: null, eventDate: "2023-09-28", observedStatus: "stalled", assertion: "OAG field inspection (28–29 Sept 2023): Gumba/Mabatini Dispensary not complete and not labelled.", excerpt: "Field inspection on these projects carried out on September 28 and 29, 2023 revealed they were not complete and labelled" },
  { key: "gm-willow-arc", projectKey: "gumba-mabatini", docKey: "willow-2026", stage: "completion", kind: "delivery_observed", amountKes: null, eventDate: "2026-07-03", observedStatus: "unusable", assertion: "Willow (July 2026): the structure was completed but water seeped through the floor, work stopped, and the building stood empty — never opened to the public.", excerpt: "Even after the structure was completed, water seeped through the floor and work stopped. The building stood empty" },
  { key: "gm-willow-end", projectKey: "gumba-mabatini", docKey: "willow-2026", stage: "completion", kind: "delivery_observed", amountKes: null, eventDate: "2026-07-03", observedStatus: "abandoned", assertion: "Willow (July 2026): the completed-but-never-used building was demolished during clearance of structures on riparian land. Only boulders remain.", excerpt: "until it was demolished during the recent clearance of structures sitting on riparian land. Only boulders now remain" },
  { key: "gm-willow-voice", projectKey: "gumba-mabatini", docKey: "willow-2026", stage: "completion", kind: "delivery_observed", amountKes: null, eventDate: "2026-07-03", observedStatus: "abandoned", assertion: "Resident testimony: the dispensary is 'a reminder of healthcare that his community was promised but never received' — Patrick Mulwa, trader near the site.", excerpt: "For Patrick Mulwa, the unfinished Gumba/Mabatini Dispensary is more than an abandoned project. It is a reminder of healthcare that his community was promised but never received." },
] as const;

